# Pytorch란 무엇인가
[PyTorch.kr](http://pytorch.kr)의 [PyTorch 60분만에 끝장내기](http://pytorch.kr/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py) 튜토리얼을 보고 따라해보는 노트
                                        

## Autograd: 자동 미분
autograd 패키지에서 Tensor의 모든 연산에 대한 미분을 제공

### Tensor

torch.Tensor 클래스에 `requires_grad` 속성을 `true`로 설정하면 `backward()`가 실행될 때마다 gradient를 자동으로 계산함, 중단하기 위해서는 `detach()`를 호출하며 중단

In [23]:
import torch
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [24]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


y는 연산의 결과임으로 grad_fn을 갖는다.

In [25]:
print(y.grad_fn)


y에 다른 연산을 수행

In [26]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


상위의 requires_grad 속성을 기본으로 상속받음

In [13]:
a = torch.randn(2, 2)
a = ((a * 3) / ( a - 1))
print(a.requires_grad)

a.requires_grad_(True)
print(a.requires_grad)

b = (a * a).sum()
print(b.grad_fn)
print(b.requires_grad)

False
True
True


### Gradient
out.backward() === out.backward(torch.tensor(1))

In [27]:
out.backward()

In [28]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
