# Pytorch란 무엇인가
[PyTorch.kr](http://pytorch.kr)의 [PyTorch 60분만에 끝장내기](http://pytorch.kr/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py) 튜토리얼을 보고 따라해보는 노트
                                        

## Tensor

In [8]:
from __future__ import print_function
import torch

초기화되지 못한 행렬을 생성

In [11]:
x = torch.empty(5, 3)
print(x)

tensor([[   0.0000,    0.0000, 1678.3075],
        [   0.0000,    0.0000,    0.0000],
        [   0.0000,    0.0000,    0.0000],
        [   0.0000,    0.0000,    0.0000],
        [   0.0000,    0.0000, 1676.8411]])


무작위로 초기화된 행렬 생성

In [15]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2618, 0.2272, 0.7990],
        [0.4001, 0.0909, 0.0778],
        [0.1390, 0.6913, 0.7855],
        [0.1633, 0.7888, 0.3370],
        [0.6266, 0.8170, 0.7803]])


0으로 채워진 행렬을 생성 (dtype를 설정할 수 있다)    
[dtype 종류](https://pytorch.org/docs/stable/tensors.html#torch-tensor)

In [23]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


직접 행렬을 텐서로 만듬

In [29]:
x = torch.tensor([5.5, 5])
print(x)

tensor([5.5000, 5.0000])


행렬의 크기를 구하기

In [31]:
x = torch.zeros(5, 3)
print(x.size())

torch.Size([5, 3])


파이토치에서의 덧셈

In [37]:
x = torch.tensor([[0, 0, 1, 1],[1, 1, 1, 1]])
y = torch.tensor([[2, 1, 2, 1],[1, 1, 1, 1]])
print(torch.add(x, y))

tensor([[2, 1, 3, 2],
        [2, 2, 2, 2]])


이렇게 할 수도 있고 (타입을 잘 신경쓰자)

In [49]:
result = torch.empty(y.size(), dtype=torch.long)
torch.add(x, y, out=result)
print(result)

tensor([[2, 1, 5, 4],
        [4, 4, 4, 4]])


이런 방법도있음 add()가 아니고 **add_()**

In [42]:
y.add_(x)
print(y)

tensor([[2, 1, 4, 3],
        [3, 3, 3, 3]])


In [52]:
print(x[:, 1])

tensor([0, 1])
